-- this file is generated by xresloader, please don't edit it.

return {
  [1] = {
    count = 10,
    data_source = {
      {
        file = "./xls/货币表.xlsx",
        sheet = "货币基本信息",
      },
    },
    data_ver = "2.13.0.20230428195913",
    hash_code = "sha256:7ab7bdbce0be6f31d0a329012411f9fdf1d24123f08889f94d25b7a6d9c284e5",
    xres_ver = "2.13.0",
  },
  [2] = "MoneyDesc",
  MoneyDesc = {
    {
      m_iMoneyID = 1,
      m_iMoneyLimit = 16000,
      m_szMoneyName = "血浆袋",
      m_szMoneyQuant = "包",
    },
    {
      m_iMoneyID = 2,
      m_iMoneyLimit = 16000,
      m_szMoneyName = "弹药袋",
      m_szMoneyQuant = "包",
    },
    {
      m_iMoneyID = 3,
      m_stExchange = {
        {
          m_iExchangeAmount = 1,
          m_iTargeMoneyID = 5,
        },
      },
      m_szMoneyName = "柑橘币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 4,
      m_stExchange = {
        {
          m_iExchangeAmount = 1,
          m_iTargeMoneyID = 3,
        },
      },
      m_szMoneyName = "幻夜币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 5,
      m_szMoneyName = "死神币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 6,
      m_stExchange = {
        {
          m_iExchangeAmount = 2,
          m_iTargeMoneyID = 7,
        },
      },
      m_szMoneyName = "金币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 7,
      m_stExchange = {
        {
          m_iExchangeAmount = 2,
          m_iTargeMoneyID = 8,
        },
        {
          m_iExchangeAmount = 1000,
          m_iTargeMoneyID = 1,
        },
        {
          m_iExchangeAmount = 1000,
          m_iTargeMoneyID = 2,
        },
      },
      m_szMoneyName = "银币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 8,
      m_szMoneyName = "铜币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 9,
      m_szMoneyName = "Q币",
      m_szMoneyQuant = "个",
    },
    {
      m_iMoneyID = 10,
      m_iMoneyLimit = 1000,
      m_szMoneyName = "欢乐豆",
      m_szMoneyQuant = "个",
    },
  },
}